CREATE SCHEMA IF NOT EXISTS weather;

GRANT ALL PRIVILEGES ON SCHEMA weather TO postgres;

CREATE TABLE IF NOT EXISTS weather.weather_data (
    city VARCHAR(100) NOT NULL,
    temp DECIMAL(5,2) NOT NULL,
    humidity INTEGER,
    pressure INTEGER,
    wind_speed DECIMAL(5,2),
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA weather TO postgres;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA weather TO postgres;
